In [1]:
import numpy as np

In [6]:
outputs = np.random.rand(1,14)
thres_a = 0.7
thres_b = 0.5
outputs

array([[0.91932709, 0.08226528, 0.66231218, 0.59388518, 0.5754154 ,
        0.83753388, 0.96548981, 0.82990603, 0.6769775 , 0.24437993,
        0.09583423, 0.95955733, 0.61529055, 0.80398372]])

In [12]:
hardlabels = ((outputs>thres_a))*1 #+ (outputs<thres_b))*1
hardlabels


array([[1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1]])

In [11]:
hardlabels = ((outputs>thres_a)*1 + (outputs<thres_b))*1
hardlabels

array([[1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1]])

In [67]:
indices = [idx for idx,value in enumerate(hardlabels.tolist()) if hardlabels[idx].all()]
indices

[0, 3]

In [66]:
hardlabels[0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])